"""Regression test for the 'Invalid JSON: Unterminated string starting at'
UI failure. A watsonx response cut off mid-string at the max_tokens limit
must be treated like any other invalid chunk response -- routed into the
existing repair/recovery machinery -- instead of crashing GenerationPipeline
with an uncaught ResponseValidationError."""
import json
from types import SimpleNamespace

from src.pipeline import GenerationPipeline


def _simple_template():
    return {
        "template_id": "simple",
        "slide_count": 1,
        "slides": [
            {
                "slide_number": 1,
                "layout_name": "Blank",
                "targets": [
                    {
                        "slide_number": 1, "target_kind": "shape", "target_id": 1, "role": "title",
                        "existing_text": "Original title", "approximate_max_characters": 60,
                        "max_content_length": 60, "required": True, "replaceable": True,
                        "position": {"left": 0, "top": 0, "width": 100, "height": 40},
                    },
                ],
            }
        ],
    }


_MESSAGE_ARGS = {"topic": "Launch", "source_content": "Facts", "audience": "Customers", "tone": "Professional", "additional_instructions": ""}


class TruncatedThenValidWatson:
    """First call is cut off mid-string, exactly like a response that hit
    max_tokens; the target is then filled through one focused-recovery call
    (an entirely blank chunk response has no structural errors of its own --
    it is just short of every required target -- so it is the recovery path,
    not the chunk-repair path, that picks it back up)."""
    def __init__(self): self.calls = 0

    def chat(self, model_id, messages, **kwargs):
        self.calls += 1
        if self.calls == 1:
            return SimpleNamespace(text='{"slides": [{"slide_number": 1, "layout_name": "Blank", "targets": [{"target_kind": "shape", "target_id": 1, "content": "Unterminated')
        return SimpleNamespace(text=json.dumps({"contents": ["Recovered title"]}))


def test_truncated_json_response_recovers_via_focused_recovery_instead_of_crashing(tmp_path):
    watson = TruncatedThenValidWatson()
    pipeline = GenerationPipeline(None, watson, tmp_path, tmp_path)
    content, warnings, calls = pipeline._generate_validated(model_id="model", template=_simple_template(), message_args=_MESSAGE_ARGS)
    assert watson.calls == 2
    assert content.slides[0].targets[0].content == "Recovered title"
    assert any("Focused recovery supplied" in warning for warning in warnings)


class AlwaysTruncatedWatson:
    """Every call -- including focused-recovery calls -- returns the same
    truncated, unparseable text."""
    def chat(self, model_id, messages, **kwargs):
        return SimpleNamespace(text='{"slides": [{"slide_number": 1, "targets": [{"content": "Still unterm')


def test_persistently_invalid_json_falls_back_to_placeholder_instead_of_crashing(tmp_path):
    pipeline = GenerationPipeline(None, AlwaysTruncatedWatson(), tmp_path, tmp_path)
    content, warnings, calls = pipeline._generate_validated(model_id="model", template=_simple_template(), message_args=_MESSAGE_ARGS)
    # Existing_text is used as the safe fallback when the model never recovers.
    assert content.slides[0].targets[0].content == "Original title"
    assert any("could not be generated by the model" in warning for warning in warnings)


def _three_slide_template():
    def slide(number):
        return {
            "slide_number": number, "layout_name": "Blank",
            "targets": [{
                "slide_number": number, "target_kind": "shape", "target_id": 1, "role": "title",
                "existing_text": f"Original title {number}", "approximate_max_characters": 60,
                "max_content_length": 60, "required": True, "replaceable": True,
                "position": {"left": 0, "top": 0, "width": 100, "height": 40},
            }],
        }
    return {"template_id": "three-slide", "slide_count": 3, "slides": [slide(n) for n in (1, 2, 3)]}


class MalformedSlideEntryWatson:
    """Reproduces the 'slides.1: Input should be a valid dictionary' UI
    failure: the model returns a well-formed object for the first slide but
    lazily emits bare strings for the rest of a multi-slide chunk response."""
    def __init__(self): self.calls = 0

    def chat(self, model_id, messages, **kwargs):
        self.calls += 1
        if self.calls == 1:
            return SimpleNamespace(text=json.dumps({
                "slides": [
                    {"slide_number": 1, "layout_name": "Blank", "targets": [{"target_kind": "shape", "target_id": 1, "content": "Real title one"}]},
                    "Slide two placeholder text",
                    "Slide three placeholder text",
                ]
            }))
        return SimpleNamespace(text=json.dumps({"contents": ["Recovered title two", "Recovered title three"]}))


def test_malformed_slide_entries_are_dropped_and_recovered_instead_of_crashing(tmp_path):
    watson = MalformedSlideEntryWatson()
    pipeline = GenerationPipeline(None, watson, tmp_path, tmp_path)
    content, warnings, calls = pipeline._generate_validated(model_id="model", template=_three_slide_template(), message_args=_MESSAGE_ARGS)
    assert watson.calls == 2
    generated = {slide.slide_number: slide.targets[0].content for slide in content.slides}
    assert generated == {1: "Real title one", 2: "Recovered title two", 3: "Recovered title three"}
    assert any("Discarded 2 malformed slide entries" in warning for warning in warnings)
